### ISSUE TITLE
Provide better feedback regarding invalid characters in file names

### ISSUE THREAD

**Issue by nicebread** [psych-ds/validator-prototype#4]
These filenames give an error, although they shouldn't:

- 8-Explore_negative–binomial.R
- 9-Select_new–picture_standard_set.R

It's due to the two minus; when I remove the second, it passes the test.

**Comment by FelixHenninger** [comment]
Wow, thanks, that really is a great find! You had me totally baffeled here for 20 minutes, but I think the validator might actually be half right in this case: it looks like the second minus is a so-called [en-dash](https://en.wikipedia.org/wiki/Dash#En_dash) (–), and not a minus (-). You can verify this by pasting the character into a character code finder like [this one](http://www.mauvecloud.net/charsets/CharCodeFinder.html), and putting a minus beside it (the output will be much more useful if you switch to HTML named character references).

That leaves us with two questions:
* Should the spec allow typographic dashes, too?
* How can be better communicate which part of the file name doesn't match? (this is the trickier question, since all we get back from the regular expression checking is a binary match/mismatch. Could we enumerate the invidual non-matching characters?)

Anyhow, I hope this clears up things 😄. Thanks for opening the issue!

-Felix

**Comment by mekline** [comment]
IMO, the spec should be limited to the typographic minus. Especially when we're writing out own code for various idiosyncratic reasons, it's desirable to be able to ask for files that include "-" and get back your datafiles; formatting the initial dataset is a great time to weed out this potential future bug. 

@nicebread, I'm curious how you generated those names though. I've most often encountered this in programs like Microsoft word where 'pretty' typesetting is a common concern (see also '...' --> '…'). Was it something like that, or did your file browser itself do this replacement? 

A pattern we might be able to rely on for spec errors in general would be to give short 'how to' instructions, and/or link out to useful documentation (once said documentation exists!!)

Would it be possible for the codebase to have these error messages stored somewhere modular so it's easy to work on their text (and any eventual links) in one place? (IE, when the validator throws this particular error, it gives ErrorMessage7, which is stored in a file or array somewhere).

For instance, for this one: 

"The following file(s) aren't passing the validator because they are in the 'data/' folder, but don't have the legal name structure. Psych-DS data file names need to end with '_data.tsv', and cannot include special characters. For more help with filenames, [placeholder for documentation link]"

**Comment by FelixHenninger** [comment]
> IMO, the spec should be limited to the typographic minus.
👍 

> Would it be possible for the codebase to have these error messages stored somewhere modular so it's easy to work on their text [...]?
That's a great idea! We are totally free in shaping the data that any error provides to our needs; for example, [here's the error data for the file name mismatch](https://github.com/psych-ds/validator-prototype/blob/master/validator-core/src/checks/filenames.js#L9). We can also already provide further information, like you propose, via a `details` key -- you can see how that works, for example, when [we report encoding mismatches](https://github.com/psych-ds/validator-prototype/blob/master/validator-core/src/checks/encoding.js#L33). The advantage of this mechanism is that we can include technical data we compute as part of the check in the error message.

We could also add a mechanism on top of that that appends further documentation based on the `message`, and pulls in information from a central message 'respository'. After looking at the mechanism above, is that still something you'd find useful?

**Comment by nicebread** [comment]
> @nicebread, I'm curious how you generated those names though. I've most often encountered this in programs like Microsoft word where 'pretty' typesetting is a common concern (see also '...' --> '…'). Was it something like that, or did your file browser itself do this replacement?

On Mac you can type an en-dash with alt-minus- I must have accidentally pressed the alt key. I agree that this should be flagged (even if it's hard for the user to spot because of the miniscule visual difference). A more specific output of course would be helpful (on the wishlist ...)

**Comment by FelixHenninger** [comment]
Hi @nicebread, I made a prototype! What do you think of this:

![Screenshot 2020-03-10 at 17 25 03](https://user-images.githubusercontent.com/8349942/76334974-21648700-62f4-11ea-99e6-ba695f71bad0.png)

**Comment by nicebread** [comment]
Wow! Beautiful and functional, great work.

**Comment by nicebread** [comment]
(could be closed IMO, but I leave it up to @FelixHenninger)

**Comment by FelixHenninger** [comment]
Thanks a lot @nicebread for your super-kind words! This change is now in master as of b0f9392d970e2eaa1a333ca12b4d12f3aedebc6a -- I had been playing with options for showing the character descriptions (e.g. 'space' instead of the decodeunicode URL), but that would have required a massive database of what every possible unicode character stands for, and that didn't seem feasible -- I hope that decodeunicode (who maintain such a database) will help folks decypher weird characters if necessary.

I'm closing this for now as it looks like the proximate goal is reached -- as always, feedback and more ideas are most welcome; thanks again for inspiring this change!

-Felix
